name: CrateUI
main: CrateUI\Main
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 1.0
author: GeoZDev

commands:
 crate:
  description: "Apri la GUI delle crates! by GeoZDev"

permissions:
 crate.key:
  description: "get key permission"
